// Voeg hier opdrachten toe, verwijder ze, of pas ze aan.
// Tip: houd minimaal 60 opdrachten over, dan krijgt iedereen echt een andere kaart.
window.BINGO_TASKS = [
  "Bestel een drankje volledig in het Frans",
  "Maak een groepsselfie in een bar",
  "Proost met iemand die je niet kent",
  "Drink een lokaal biertje",
  "Eet een portie friet",
  "Maak een foto met een neonbord",
  "Zing mee met een nummer in de kroeg",
  "Doe een dansje van 10 seconden",
  "Laat de barman of barvrouw lachen",
  "Geef iemand uit de groep een compliment",
  "Vind iemand met dezelfde voornaamletter",
  "Maak een foto van het gekste glas",
  "Bestel water zonder je te verontschuldigen",
  "Maak een foto bij de Vieille Bourse",
  "Doe een groepsproost buiten op straat",
  "Leer één Frans woord van een local",
  "Laat iemand anders je drankje kiezen",
  "Speel steen-papier-schaar met een vreemde",
  "Maak een selfie met een local",
  "Vraag om een muziektip",
  "Doe alsof je een toeristengids bent",
  "Maak een foto van een hond",
  "Maak een foto van een straatmuzikant",
  "Vind een bar met een grappige naam",
  "Drink iets dat je normaal nooit bestelt",
  "Betaal een rondje voor iemand",
  "Zeg 'santé' tegen een vreemde",
  "Vraag iemand naar zijn favoriete bar in Lille",
  "Maak een foto van de hele groep met duimen omhoog",
  "Doe een mini-polonaise",
  "High-five drie mensen uit de groep",
  "Vind iemand die jarig is deze maand",
  "Maak een foto van de mooiste deur/gevel",
  "Doe een karaoke-moment zonder microfoon",
  "Laat iemand een bijnaam voor je verzinnen",
  "Maak een foto waarop iedereen serieus kijkt",
  "Maak direct daarna dezelfde foto lachend",
  "Bestel de goedkoopste drank op de kaart",
  "Bestel de duurste drank op de kaart",
  "Vind een cocktail met een Franse naam",
  "Laat de groep stemmen op jouw beste dansmove",
  "Maak een teamfoto in spiegelbeeld",
  "Proost met links",
  "Maak een foto van een menukaart met typefout",
  "Vraag de weg in het Frans",
  "Noem drie Franse artiesten",
  "Vind iemand met een voetbalshirt",
  "Laat iemand een toast uitspreken",
  "Maak een foto met iets geels",
  "Maak een foto met iets paars",
  "Doe 20 seconden alsof je DJ bent",
  "Laat iemand anders je volgende opdracht kiezen",
  "Speel een kort drinkspelletje",
  "Maak een foto van een bijzonder plafond",
  "Vind een bar met live muziek of een DJ",
  "Maak een selfie met de kortste persoon uit de groep",
  "Maak een selfie met de langste persoon uit de groep",
  "Vraag een local om een groepsfoto te maken",
  "Vind iemand die Nederlands spreekt",
  "Vind iemand die geen Frans spreekt",
  "Bestel iets zonder Engels te gebruiken",
  "Maak een foto met een fiets",
  "Eet iets hartigs na 22:00",
  "Drink een drankje zonder alcohol",
  "Doe een cheers-boomerang of korte video",
  "Bedenk een teamleus en roep hem samen",
  "Laat iemand uit de groep een mop vertellen",
  "Maak een foto van een opvallende lamp",
  "Vind een bar met rode verlichting",
  "Maak een foto bij een plein",
  "Vraag naar de beste snack van Lille",
  "Laat iemand je Franse uitspraak beoordelen",
  "Maak een foto met een onbekend woord op een bord",
  "Doe een catwalk door de groep",
  "Maak een selfie met iemand die een bril draagt",
  "Vind iemand die dezelfde drank bestelt als jij",
  "Speel 'ik zie ik zie wat jij niet ziet' in de bar",
  "Maak een foto van schoenen van de hele groep",
  "Laat iemand een liedje inzetten",
  "Noem drie dingen die je vandaag in Lille zag",
  "Vraag om een servet als souvenir",
  "Laat de groep jouw drankje een cijfer geven",
  "Maak een foto met een kunstwerk of poster",
  "Vind een plek waar je buiten kunt zitten",
  "Proost op de organisator",
  "Laat de groep één minuut geen Nederlands praten",
  "Maak een foto van het raarste object in de bar",
  "Vind een bar waar niemand eerder is geweest",
  "Doe een dramatische entree bij de volgende bar",
  "Laat iemand een quote van de avond opschrijven",
  "Vraag om een stempel, sticker of bierviltje",
  "Maak een foto met een Frans vlaggetje",
  "Bedenk een bijnaam voor deze bar",
  "Doe een mini-interview met iemand uit de groep",
  "Bestel iets dat begint met de eerste letter van je naam",
  "Laat iemand je outfit omschrijven in drie woorden",
  "Maak een foto van een klok",
  "Vind iets met het woord 'Lille' erop",
  "Kies de volgende bar op basis van de naam",
  "Neem een groepsfoto vóór het verlaten van een bar",
  "Eindig een zin met 'oui oui'"
];
